export type ProviderGuide={id:string;name:string;category:'ایرانی'|'جهانی'|'آفلاین';symbol:string;accent:string;description:string;url:string;steps:string[];env?:string;tips:string};
export const providerGuides:ProviderGuide[]=[
{id:'avalai',name:'AvalAI',category:'ایرانی',symbol:'آ',accent:'#37c6a0',description:'درگاه API ایرانی برای استفاده از مدل‌های پشتیبانی‌شده.',url:'https://avalai.ir',env:'AVALAI_API_KEY',steps:['در سایت رسمی ثبت‌نام کن و از پنل خود کلید API بگیر.','کلید را در متغیر محیطی AVALAI_API_KEY سیستم ذخیره کن.','کیو را دوباره باز کن؛ AvalAI را انتخاب و شناسه مدل فعال حساب خودت را وارد کن.','یک پیام کوتاه بفرست تا پاسخ و وضعیت اتصال را بررسی کنی.'],tips:'مدل‌ها، اعتبار و تعرفه به پنل حساب بستگی دارند.'},
{id:'hooshgar',name:'هوشگر',category:'ایرانی',symbol:'ه',accent:'#edaf70',description:'درگاه ایرانی با اتصال API سازگار، در صورت فعال بودن حساب.',url:'https://hooshgar.ir',env:'HOOSHGAR_API_KEY',steps:['مستندات و دسترسی API را در وب‌سایت رسمی بررسی کن.','کلید API معتبر را در HOOSHGAR_API_KEY سیستم قرار بده.','برنامه را مجدد راه‌اندازی کن و شناسه مدل ارائه‌شده را وارد کن.','ابتدا با پیام کوتاه اتصال را آزمایش کن.'],tips:'پیش از استفاده، فعال‌بودن API و آدرس سرویس را در پنل رسمی بررسی کن.'},
{id:'openai',name:'OpenAI',category:'جهانی',symbol:'◎',accent:'#56b9a1',description:'گفت‌وگوی مستقیم با مدل‌های حساب OpenAI از طریق API.',url:'https://platform.openai.com',env:'OPENAI_API_KEY',steps:['در پلتفرم رسمی، دسترسی API و صورتحساب را بررسی کن.','API Key را بساز و در OPENAI_API_KEY سیستم تنظیم کن.','مدل مجاز حساب را در کیو وارد کن.','ارسال پیام را آزمایش کن.'],tips:'اشتراک ChatGPT و اعتبار API یکی نیستند.'},
{id:'openrouter',name:'OpenRouter',category:'جهانی',symbol:'↗',accent:'#c2a4fb',description:'یک درگاه برای مدل‌های گوناگون با شناسه‌های مخصوص.',url:'https://openrouter.ai',env:'OPENROUTER_API_KEY',steps:['در وب‌سایت OpenRouter حساب بساز و کلید API دریافت کن.','متغیر OPENROUTER_API_KEY را تنظیم کن.','شناسه کامل مدل را از فهرست رسمی کپی کن.','مدل را در کیو انتخاب و یک پیام آزمایشی ارسال کن.'],tips:'بعضی مدل‌ها رایگان یا محدود و برخی هزینه‌دار هستند.'},
{id:'deepseek',name:'DeepSeek',category:'جهانی',symbol:'◇',accent:'#7aa9f9',description:'مدل‌های DeepSeek از طریق درگاه مستقیم API.',url:'https://platform.deepseek.com',env:'DEEPSEEK_API_KEY',steps:['به پنل DeepSeek وارد شو و دسترسی API را آماده کن.','کلید را به DEEPSEEK_API_KEY سیستم اضافه کن.','شناسه دقیق مدل مجاز را از مستندات بردار.','پاسخ را با یک پرسش ساده بررسی کن.'],tips:'نام مدل و موجودی API ممکن است تغییر کند.'},
{id:'groq',name:'Groq',category:'جهانی',symbol:'⚡',accent:'#f3a269',description:'سرویس استنتاج سریع برای مدل‌های پشتیبانی‌شده.',url:'https://console.groq.com',env:'GROQ_API_KEY',steps:['در Groq Console کلید API بساز.','متغیر GROQ_API_KEY را تنظیم کن.','شناسه مدل پشتیبانی‌شده حساب را وارد کن.','پیام آزمایشی ارسال کن.'],tips:'محدودیت نرخ درخواست متناسب با حساب است.'},
{id:'together',name:'Together AI',category:'جهانی',symbol:'✳',accent:'#f7c56d',description:'مدل‌های ابری متن‌باز و اختصاصی از طریق API.',url:'https://api.together.ai',env:'TOGETHER_API_KEY',steps:['در Together AI حساب و کلید API ایجاد کن.','TOGETHER_API_KEY را در سیستم تنظیم کن.','شناسه مدل از فهرست رسمی انتخاب کن.','کیو را باز و پاسخ آزمایشی بگیر.'],tips:'مدل‌ها باید با Chat Completions سازگار باشند.'},
{id:'mistral',name:'Mistral AI',category:'جهانی',symbol:'M',accent:'#ff9a61',description:'مدل‌های Mistral از مسیر رسمی و سازگار با Chat Completions.',url:'https://console.mistral.ai',env:'MISTRAL_API_KEY',steps:['به Mistral Console برو و دسترسی API را فعال کن.','کلید را در MISTRAL_API_KEY سیستم تنظیم کن.','شناسه یکی از مدل‌های فعال حساب را بردار.','کیو را دوباره باز کن و ارسال پیام را تست کن.'],tips:'مدل پیشنهادی باید با Chat Completion سازگار باشد.'},
{id:'xai',name:'Grok (xAI)',category:'جهانی',symbol:'X',accent:'#b3bccd',description:'اتصال مستقیم به مدل‌های Grok از API رسمی xAI.',url:'https://console.x.ai',env:'XAI_API_KEY',steps:['در کنسول xAI، حساب و دسترسی API را بررسی کن.','کلید API را در XAI_API_KEY تنظیم کن.','شناسه مدل Grok موجود در حساب را وارد کن.','پیام ساده‌ای بفرست و پاسخ را بررسی کن.'],tips:'این اتصال به API است و به حساب شبکه اجتماعی متکی نیست.'},
{id:'fireworks',name:'Fireworks AI',category:'جهانی',symbol:'✦',accent:'#f19b8b',description:'اجرای مدل‌ها در سرویس Fireworks با API رسمی.',url:'https://fireworks.ai',env:'FIREWORKS_API_KEY',steps:['در Fireworks کلید API بساز.','آن را در FIREWORKS_API_KEY سیستم تنظیم کن.','شناسه مدل Chat Completions را از داشبورد کپی کن.','بعد از راه‌اندازی مجدد کیو، یک پیام آزمایشی ارسال کن.'],tips:'شناسه مدل‌ها معمولاً طولانی است؛ دقیق کپی کن.'},
{id:'cerebras',name:'Cerebras',category:'جهانی',symbol:'C',accent:'#b7e899',description:'API سریع برای مدل‌های سازگار با Chat Completions.',url:'https://cloud.cerebras.ai',env:'CEREBRAS_API_KEY',steps:['در Cerebras Cloud حساب و API Key بساز.','CEREBRAS_API_KEY را در سیستم ثبت کن.','مدل فعال در حساب خود را انتخاب کن.','پس از بازکردن کیو، پاسخ را آزمایش کن.'],tips:'فهرست مدل‌های پشتیبانی‌شده و سقف درخواست‌ها متغیر است.'},
{id:'ollama',name:'Ollama',category:'آفلاین',symbol:'◉',accent:'#7ddcc9',description:'اجرای مدل روی کامپیوتر خودت؛ بدون کلید API ابری.',url:'https://ollama.com/download',steps:['Ollama را از سایت رسمی برای Windows یا macOS نصب کن.','در ترمینال با ollama pull شناسه مدل دلخواه را دانلود کن.','سرویس Ollama را روی دستگاه اجرا نگه دار.','در کیو Ollama را انتخاب و نام همان مدل محلی را وارد کن.'],tips:'دانلود اولیه مدل اینترنت می‌خواهد؛ اجرای بعدی می‌تواند محلی باشد و منابع RAM کافی لازم است.'},
{id:'lmstudio',name:'LM Studio',category:'آفلاین',symbol:'▣',accent:'#9faef2',description:'اجرای مدل دانلودشده و سرور محلی Chat Completions.',url:'https://lmstudio.ai',steps:['LM Studio را از وب‌سایت رسمی نصب کن.','مدل مناسب سخت‌افزار خودت را دانلود و Load کن.','بخش Local Server را باز و سرور API را فعال کن.','در کیو LM Studio را انتخاب و شناسه مدل بارگذاری‌شده را وارد کن.'],tips:'اگر سرور محلی روشن نباشد، اتصال برقرار نمی‌شود.'}
];
